{% set version = "5.0.0" %}

package:
  name: nbconvert
  version: {{ version }}

source:
  fn: nbconvert-{{ version }}.tar.gz
  url: https://github.com/jupyter/nbconvert/archive/{{ version }}.tar.gz
  sha256: 9def08d46dbb3129c3056d6ec878e67a23a7e1a82fdc55525a1081c29879fe2e

build:
  number: 0
  script: pip install --no-deps .
  entry_points:
    - jupyter-nbconvert = nbconvert.nbconvertapp:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - mistune >0.6
    - jinja2
    - pygments
    - traitlets
    - jupyter_core
    - nbformat
    - entrypoints
    - pandocfilters

test:
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.tests
    - nbconvert.utils
    - nbconvert.writers

  commands:
    - jupyter-nbconvert --help

about:
  home: http://jupyter.org
  license: BSD 3-Clause
  summary: 'Converting Jupyter Notebooks'

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
