{% set version = "6.5.4" %}

package:
  name: nbconvert
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbconvert/nbconvert-{{ version }}.tar.gz
  sha256: 9e3c7c6d491374cbdd5f35d268c05809357716d346f4573186bbeab32ee50bc1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-nbconvert = nbconvert.nbconvertapp:main
    - jupyter-dejavu = nbconvert.nbconvertapp:dejavu_main
  skip: True  #[py<37]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - beautifulsoup4
    - bleach
    - defusedxml
    - entrypoints >=0.2.2
    - jinja2 >=2.4
    - jupyter_core
    - jupyterlab_pygments
    - mistune >=0.8.1,<2
    - nbclient >=0.5.0,<0.6.0
    - nbformat >=4.4
    - pandocfilters >=1.4.1
    - pygments >=2.4.1
    - traitlets >=5.0
    - testpath
  run_constrained:
    - pyppeteer >=1,<1.1

test:
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.tests
    - nbconvert.utils
    - nbconvert.writers
  source_files:
    - nbconvert/tests/files/notebook1.ipynb

  requires:
    - pip
    - beautifulsoup4
  commands:
    - pip check
    - jupyter nbconvert --help
    - jupyter nbconvert nbconvert/tests/files/notebook1.ipynb --to html

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Converting Jupyter Notebooks
  description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other
    formats via Jinja templates. The nbconvert tool allows you to convert an
    .ipynb notebook file into various static formats.
  doc_url: https://nbconvert.readthedocs.org/
  dev_url: https://github.com/jupyter/nbconvert

extra:
  recipe-maintainers:
    - jakirkham
    - mpacer
    - minrk
    - pelson
    - takluyver
    - mseal
    - blink1073
    - ocefpaf
