{% set version = "6.2.0" %}

package:
  name: nbconvert
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbconvert/nbconvert-{{ version }}.tar.gz
  sha256: 16ceecd0afaa8fd26c245fa32e2c52066c02f13aa73387fffafd84750baea863

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-nbconvert = nbconvert.nbconvertapp:main
  skip: True  #[py<37]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - mistune >=0.8.1,<2
    - jinja2 >=2.4
    - pygments >=2.4.1
    - traitlets >=5.0
    - jupyter_core
    - nbformat >=4.4
    - entrypoints >=0.2.2
    - bleach
    - pandocfilters >=1.4.1
    - testpath
    - defusedxml
    - nbclient >=0.5.0,<0.6.0
    - jupyterlab_pygments
  run_constrained:
    - pyppeteer ==0.2.2

test:
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.tests
    - nbconvert.utils
    - nbconvert.writers
  source_files:
    - nbconvert/tests/files/notebook1.ipynb

  requires:
    - pip
  commands:
    - pip check
    - jupyter nbconvert --help
    - jupyter nbconvert nbconvert/tests/files/notebook1.ipynb --to html

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Converting Jupyter Notebooks
  description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other
    formats via Jinja templates. The nbconvert tool allows you to convert an
    .ipynb notebook file into various static formats.
  doc_url: http://nbconvert.readthedocs.org/
  dev_url: https://github.com/jupyter/nbconvert

extra:
  recipe-maintainers:
    - jakirkham
    - mpacer
    - minrk
    - pelson
    - takluyver
    - mseal
    - blink1073
    - ocefpaf
