{% set version = "5.1.1" %}

package:
  name: nbconvert
  version: {{ version }}

source:
  fn: nbconvert-{{ version }}.tar.gz
  url: https://github.com/jupyter/nbconvert/archive/{{ version }}.tar.gz
  sha256: 847731bc39829d0eb1e15a450ac98c71730e3598e53683d4d76a3f3b3fc5017d 

build:
  number: 1
  script: pip install --no-deps .
  # skip py36 while waiting for dependencies
  skip: True  # [py36]
  entry_points:
    - jupyter-nbconvert = nbconvert.nbconvertapp:main

requirements:
  build:
    - python
    - pip
  run:
    - bleach
    - entrypoints >=0.2.2
    - jinja2
    - jupyter_core
    - mistune >0.6
    - nbformat
    - pandoc
    - pandocfilters >=1.4.1
    - python
    - pygments
    - testpath
    - traitlets

test:
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.tests
    - nbconvert.utils
    - nbconvert.writers

  commands:
    - jupyter-nbconvert --help

about:
  home: http://jupyter.org
  license: BSD 3-Clause
  summary: 'Converting Jupyter Notebooks'

extra:
  recipe-maintainers:
    - jakirkham
    - michaelpacer
    - minrk
    - pelson
    - takluyver
