{% set version = "7.8.0" %}

package:
  name: nbconvert
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbconvert/nbconvert-{{ version }}.tar.gz
  sha256: f5bc15a1247e14dd41ceef0c0a3bc70020e016576eb0578da62f1c5b4f950479

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-nbconvert = nbconvert.nbconvertapp:main
    - jupyter-dejavu = nbconvert.nbconvertapp:dejavu_main
  skip: True  #[py<37]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - beautifulsoup4
    - bleach
    - defusedxml
    - entrypoints >=0.2.2
    - jinja2 >=3.0
    - jupyter_core >=4.7
    - jupyterlab_pygments
    - lxml
    - markupsafe >=2.0
    - mistune >=0.8.1,<2
    - nbclient >=0.5.0
    - nbformat >=5.1
    - packaging
    - pandocfilters >=1.4.1
    - pygments >=2.4.1
    - traitlets >=5.0
    - tinycss2
  run_constrained:
    - pyppeteer >=1,<1.1

test:
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.tests
    - nbconvert.utils
    - nbconvert.writers
  source_files:
    - nbconvert/tests/files/notebook1.ipynb

  requires:
    - pip
    - beautifulsoup4
  commands:
    - pip check
    - jupyter nbconvert --help
    - jupyter nbconvert nbconvert/tests/files/notebook1.ipynb --to html

about:
  home: https://nbconvert.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Converting Jupyter Notebooks
  description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other
    formats via Jinja templates. The nbconvert tool allows you to convert an
    .ipynb notebook file into various static formats.
  doc_url: https://nbconvert.readthedocs.io/en/latest/
  dev_url: https://github.com/jupyter/nbconvert

extra:
  recipe-maintainers:
    - jakirkham
    - mpacer
    - minrk
    - pelson
    - takluyver
    - mseal
    - blink1073
    - ocefpaf
