{% set name = "nbconvert" %}
{% set version = "7.16.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86ca91ba266b0a448dc96fa6c5b9d98affabde2867b363258703536807f9f7f4

build:
  number: 0
  skip: True  #[py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - jupyter-nbconvert = nbconvert.nbconvertapp:main
    - jupyter-dejavu = nbconvert.nbconvertapp:dejavu_main

requirements:
  host:
    - python
    - pip
    - hatchling >=1.5
  run:
    - python
    - beautifulsoup4
    - bleach !=5.0.0
    - defusedxml
    - importlib-metadata >=3.6  # [py<310]
    - jinja2 >=3.0
    - jupyter_core >=4.7
    - jupyterlab_pygments
    - markupsafe >=2.0
    - mistune >=2.0.3,<4
    - nbclient >=0.5.0
    - nbformat >=5.7
    - packaging
    - pandocfilters >=1.4.1
    - pygments >=2.4.1
    - traitlets >=5.1
    - tinycss2
  run_constrained:
    - pyqtwebengine >=5.15
    - tornado >=6.1

test:
  imports:
    - nbconvert
    - nbconvert.exporters
    - nbconvert.filters
    - nbconvert.postprocessors
    - nbconvert.preprocessors
    - nbconvert.resources
    - nbconvert.utils
    - nbconvert.writers
  source_files:
    - tests
  requires:
    - pip
    - pytest >=7
    - ipykernel
    - ipywidgets >=7
    - flaky
  commands:
    - pip check
    - jupyter nbconvert --version
    - jupyter dejavu --version
    - jupyter nbconvert --help
    - jupyter dejavu --help
    - jupyter nbconvert tests/files/notebook1.ipynb --to html
    # skipping test_post_processor and test_convert_full_qualified_name as they expect tests to be a module
    - pytest -v -k "not (test_post_processor or test_convert_full_qualified_name)"

about:
  home: https://nbconvert.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Converting Jupyter Notebooks
  description: |
    The nbconvert tool, jupyter nbconvert, converts notebooks to various other
    formats via Jinja templates. The nbconvert tool allows you to convert an
    .ipynb notebook file into various static formats.
  doc_url: https://nbconvert.readthedocs.io
  dev_url: https://github.com/jupyter/nbconvert

extra:
  recipe-maintainers:
    - jakirkham
    - mpacer
    - minrk
    - pelson
    - takluyver
    - mseal
    - blink1073
    - ocefpaf
