travis:
  secure:
    BINSTAR_TOKEN: cqykPcITK8G6aXGV8PndR/hFf8t6mPy1hICU2ylhsVhpNxoKMHAMbew0xoL1iIQZ1NEJddRFXi2zlJfW30hxddF08UPOZyKRxOPP8sasWud/YzrdauaNkHZ9x3p2Q8GWrIpjfWlrXBi7Xihz9y9zhUCWkU2d87kc9x8cW7h4xOFbxSUR9dChFv1AI2/Dzb21ByhmhSFtq546WmpaxrISnX3yICWr444R4tiRUJWYULdjEL0m5t1pWbOk2B84flrnFOsirFmlhavcH3USLN+L54iixZ5Mt0W80SNGQySz3h047nh4YY1yXA/uu9D4wJEAszU8Aev7y9pUygP/rMA4hUCFz+cGtYKifJyWiwhgqFboLFS7Dda0d8obPpQkIL5liSDlBZcGhEiJ7BsH/2UXO+Q1Qmx01iMrGqqltYAnvh8w9W1d71VBUuU5bpopCLuJwy1xMJwSf6SwdOQsiy7woR/knb0vvm2zKSki1/BYzkisJ/rLY+8vu/OTdpBK+h7WLAxslGjDa5XjJNT1Iv6z2gUm1s0tLh7u2d8hqsZrVz7zmuWJ+ktKKgp7iQFW8I5T/AWkl7iXYzmvRP6y14Bn+dp8qcQjxLYzzDn36hPmiwvdoPWQ0p4pU9iSt2ipzV3EWUbBWoRCVE9WgPbFaaFCOuG3eRAVpd3ts474p7z1fOU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
