travis:
  secure:
    BINSTAR_TOKEN: Xg1GPpR9i9/Y1Uz5sqg+e5I7C0msKDNZuuHJx0YdSXakp8Xe2Pxg7ouqsWO46m1UkGF1orhxdP3x37WEL3GazBt/9KZVEIo08OrcI+TRBpfNUBtpqNihQc9OgnBGIBLkuKSoovhll4INoWcYx9yPHQaKgNN9C/n2fOIR1DH2flphrnVQ6BvinHyFdU7DZ5fuCCJulxFrO9CVmlFtbSw4q4oPiaulQiuF1AJ1np7GS7lxB5XzVwyoKqeU66Ets1R9s1bO7SPtbJEhb8nZMeenIOmbcjRY488tykGrLu8Z6NelFCx5qcEw8VKtBOzapsD1i7cVJIHw/PpNtCX8ZBI8gpfDO5lh3uxQeRe4PXOU51VM0YI3txcWwHc252ms49Ct7a4OayeD4k9g3byTk4n4GaG1JTc2T1qHC4j0+4t7EujyXVi6uLgmlLC0HuUe7QloNnKasOPPWYFHWFqxkqoeFk3xO9OfVCkUm+SATIfufNr/XL21ECINzBzj8oAg3G6qM1wFhcc4wvrMzkZu71u0/D4a9ECARI2RjYxQhIskAxdJJne2P7mNpWnFoBT8KSQcNLdGUAoKMKL26hdYvaeNxEKjuPXgV1Za+aBVO3ZhJTx3ARKk7wJgm4bn79NehPPeM0dxsl8+jwlOVVOvscsEvYmlTUofBVrMkPsJ6ORR+o4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
