travis:
  secure:
    BINSTAR_TOKEN: tuUyxx1ZF35gqQUUVFMTDk9HADRzL3AryS84MZUC5CBaEcnXuqs82PzGiDd6+35UaNX+xXWr6RnKHba+aQzBkIhchZ45PiYCail34dVh5e+eVcTSC9t1JHkBy2YYv3axOe5OJHGU4sLpa+33fKZrFB5+00qc9mjedslACz8xARay6IGgKL6z+Nlsw3322KH7Wcr+DYw54prU5qcsRQlFRusdUOSaT6c/ZW4Los3zYejtir9PXTSvFVT0s5oHJH9XIGNCRzAQU4RZwddFOfNG3U02OPdtz5uXsX64hxv7zE8IYhW11z+mwKdgfzLSwyBwPtBR4zxzSxp+JE4Q8cGk6XNsfNXfC4x9NOtBj0BA0nrL4TiC1ov2fr+F706G1HzOak/swMg+fJvNhlB9q0g4nK/c/j6fIaLK47r1n/FH3MkfOtJyqm/2tcHKfmsHwPq4ggl6OlpTxEb4DYSNMznPjQrM6YA02om8kct7omvhvGnNp18IG29ZAq5zUJDGN50zbfZ41z34SACQ8KTOgITD5IHz9fzusdeU7NUeJx+yj7UALhCOu8KdnTW6uJfsf97WSj2ob7sQ9gwxK50U0t/kX4RtHKXKzlz9uwr+TceOuvUvNzH1pgEd6ylC3hYuEejUwT4T7I+yCrokKLe9gBAH56hHkOT5oJ1DsfwZPsth3zA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
